Fix :  상호작용 이벤트 구독 해제 및 퍼널 적용하기
MissingReferenceException: The object of type 'Button' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
해결 완료